In [1]:
from scipy.io import loadmat
from matplotlib import pyplot as plt
import numpy as np
from sklearn.linear_model import LinearRegression
%matplotlib widget

In [2]:
arr = loadmat('/mnt/c/Users/serge/OneDrive/Documents/MATLAB/CAQM/examples/figures/timing_get_c_from_d_H_mlx_arr.mat')

In [3]:
ns, ms, c_plus_time, c_minus_time = arr['plot_ns'][0], arr['plot_ms'][0], arr['plot_c_plus_time'][0], arr['plot_c_minus_time'][0]

In [4]:
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')

ax.scatter(ns, ms, c_plus_time)
plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [6]:
ns_log = np.log10(ns)
ms_log = np.log10(ms)
t_log_plus = np.log10(c_plus_time)
t_log_minus = np.log10(c_minus_time)

In [7]:
def X_from_nm_log(ns_log, ms_log):
    X = np.array([ns_log, ms_log, np.exp(ns_log), np.exp(ms_log), np.multiply(ns_log, ms_log),
                  
                  np.exp(np.multiply(ns_log, ms_log))]).T
    return X
X = X_from_nm_log(ns_log, ms_log)
y = t_log_minus#plus

In [8]:
X.shape

(2842, 6)

In [9]:
lr = LinearRegression()
lr.fit(X, y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [10]:
lr.predict(X)

array([-0.77031374, -0.42382073,  0.8295014 , ...,  0.1129868 ,
        0.45418525,  0.54009557], dtype=float32)

In [11]:
lr.coef_

array([-1.9134682 , -0.5607573 ,  0.52768224,  0.09085371,  0.4052508 ,
        0.00751156], dtype=float32)

In [12]:
def range_from_arr(a):
    m, M = np.min(a), np.max(a)
    return np.linspace(m, M, 100)

fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')



ax.scatter(ns_log, ms_log, t_log_plus, alpha=0.4)
ax.scatter(ns_log, ms_log, lr.predict(X), alpha=0.4)


# ns1 = range_from_arr(ns_log)
# ms1 = range_from_arr(ms_log)
# ns1, ms1 = np.meshgrid(ns1, ms1)
# yp = X_from_nm_log(ns1, ms1)
# ax.plot_surface(ns_log, ms_log, lr.predict(yp), alpha=0.5)

plt.show()

Canvas(toolbar=Toolbar(toolitems=[('Home', 'Reset original view', 'home', 'home'), ('Back', 'Back to previous …

In [57]:
ns1

array([[0.60205078, 0.61617148, 0.63029218, ..., 1.9717586 , 1.9858793 ,
        2.        ],
       [0.60205078, 0.61617148, 0.63029218, ..., 1.9717586 , 1.9858793 ,
        2.        ],
       [0.60205078, 0.61617148, 0.63029218, ..., 1.9717586 , 1.9858793 ,
        2.        ],
       ...,
       [0.60205078, 0.61617148, 0.63029218, ..., 1.9717586 , 1.9858793 ,
        2.        ],
       [0.60205078, 0.61617148, 0.63029218, ..., 1.9717586 , 1.9858793 ,
        2.        ],
       [0.60205078, 0.61617148, 0.63029218, ..., 1.9717586 , 1.9858793 ,
        2.        ]])

In [56]:
lr.predict(np.zeros((3, 3))

SyntaxError: unexpected EOF while parsing (<ipython-input-56-0134db816c7e>, line 1)

In [16]:
np.mean(ns == ms) * 100

0.8092892329345531